### ISSUE TITLE
Recommendation:  Add space between emoji and text

### ISSUE THREAD

**Issue by mikeerickson** [fraxken/publish-preview#1]
Just a small UI tweak, suggest adding some space between emoji and start of text (see screenshot)

![image](https://user-images.githubusercontent.com/183153/50727973-f5d68300-10d7-11e9-97c7-e905a252abd5.png)

**Comment by fraxken** [comment]
hi,

That was already implemented on master (but was not yet publish on npm). Version 1.3.0 is now available and there should be a space.

best regards,
Thomas
